### PR TITLE
fix: various typos in README and code

### PR DESCRIPTION
**Pull request by ccoVeille**
I noticed a few typo errors and wording.

Here is a PR to fix them.

### CODE REVIEW

**Review by isabelroses — COMMENTED** [review]
macOS is the correct format see https://en.wikipedia.org/wiki/MacOS.

**Comment by ccoVeille** [comment]
Indeed, I'm sorry, let me fix.

**Comment by ccoVeille** [comment]
pushed back, please review

**Review by meowgorithm — APPROVED** [review]

**Comment by maaslalani** [comment]
Thank you so much @ccoVeille!

**Pull request merged**
